---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-admin-secret
  namespace: auth
spec:
  encryptedData:
    admin-password: AgAT9giPvjy8yNMQJYNrpqIwajvUpQTRDLUygAGuxOBUIWTwKP2dfs0b3DiG0Gl9zr9H/qKALiDdmpUv6vqUnZ9PuiQ0AlFRtnHQmvTocJR60TdYvemKfwHIGPsOLuPvDg4T7jK22KVIiJUVVigyyW5Y2EXMJ9M/M6WIBvIYsyYkVdzPYO9n+P+gko4o0Zt+lu19wAsd+hKzJYVmRXtDO0QoTQ+76F0rrU4VmSQWDHNafEXHvlGJ1fwEzDtJMu0B9zOyAryPd/qydOjmQA7LyC+t29ldNJcFWpCXNYKgeCQQAO4mP2MlWeyu2sXy0kMZ7ohRV6tszbWxSl7FytYrHUEc8jo5+ws8JD+b6fuF/8fKbRwW9V7C3qBmJnO95vf0fg/li3wAKu5B1Be1bMjdALeOedUOj2l7wSd6ifvBiExEl1QvTjIL3qGHfUZNWbJi1PfbO/bNsbHr8icu8tfsqYJFtkc6ExlYI3fQsULcrXR5d+cu2A+0iueM5EXZjDddCcnAWOFe8FDlk7cjhhdvzsw6vjw580PWhxeXLEr66IerNFLxc148erYvlUfD8IVY5uqIzE6Z0lLIn0iVPCgOjjCHCFxN5Yv7vAN40KgIk3XbdQMCB254TlKueonaXgpQnAtH9TWboV1vURA1t6ya66rPxCBZAr5cLVz60ilkDOcTOf+am2Mpd1znu8hd9Gp6Ivi43VJbzwDdfQ==
    admin-user: AgCbm9SBjREa+1DDKpwPKOPb4g3RxCi7BKSg7+9D1DsZpXuGKWL3cW4hU9oHMKtkhFwim7ZGOgF3TWwxjP6qXUW55jhKNXCUYUUlqcluC65GfkRfNXXImzaWK6PpCd836mZqesmocBr6+9zUDTVyPyKHGi/RzojbodpnMYqYl1Demy7/YQxuLqpWwI+wutaovxKT0FSjRRkAyjLbqZdj+wWunwp7H9j8CGh6Q4ySNPJgifxg6CldiEn8ax7jgxZeu+4m+Bzt6gLl8QwGaKgLsDcwbf7BjKSG3c29O40VwJnzeW0xUlIIF86PpwpPCjKMKfSVIIGlxY6YzBkGTKhc6FuHHwcuJCeU/59UwOoxRJUOA01ysLMqbt9VUGzJoyswdsZbfQ/iUZXTEMINrZtuQ+NIrFnp37xPEift0dmVm1BFnr3aZeQ4kXpy+U4ktz6rSjUOpMBnemMzvMVxzhBZvw4FLrnHZRr41jyZHy9vdhwPedt1vYuq3XKB3nOBLkkp+xFFRve0vxNzZOjcGWm5+qeA7YuAJQpWw+iXEtkYNXZ1jiAr5Oe3uTTgj8E1id8P5AEXL4RMegC/TOZHceskkktagfMqTQgSDILnp0doeCxYqDxlzTNafdCWWAJDGjdLzB1PJv47jWLk1+55WArx3CnE5shrasGksn9pAsnlt/3VEeav1pGZe3PSo0jkkQS9YD176m/A/w==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-admin-secret
      namespace: auth
