# Root Application - App-of-Apps Pattern
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/Z3ROX-lab/ai-security-platform
    targetRevision: master
    path: argocd/applications
    directory:
      recurse: true
      include: '**/application.yaml'   # ← Seulement les application.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
